DryFood/DryFood/Areas/Admin/Controllers/DONHANGsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DryFood.Areas.Admin.Data;

namespace DryFood.Areas.Admin.Controllers
{
    public class DONHANGsController : Controller
    {
        private dryfoodEntities db = new dryfoodEntities();

        // GET: Admin/DONHANGs
        public ActionResult Index()
        {
            var dONHANG = db.DONHANG.Include(d => d.KHACHHANG).Include(d => d.KHUYENMAI).Include(d => d.PTTT);
            return View(dONHANG.ToList());
        }

        // GET: Admin/DONHANGs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONHANG dONHANG = db.DONHANG.Find(id);
            if (dONHANG == null)
            {
                return HttpNotFound();
            }
            return View(dONHANG);
        }

        // GET: Admin/DONHANGs/Create
        public ActionResult Create()
        {
            ViewBag.MaKH = new SelectList(db.KHACHHANG, "MaKH", "Ho");
            ViewBag.MaKM = new SelectList(db.KHUYENMAI, "MaKM", "TenKM");
            ViewBag.MaPTTT = new SelectList(db.PTTT, "MaPTTT", "TenPTTT");
            return View();
        }

        // POST: Admin/DONHANGs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "MaDH,NoiGiao,NgayDat,NhanXet,MaKH,MaKM,MaPTTT,TamTinh,ThanhTien,MaTrangThai")] DONHANG dONHANG)
        {
            if (ModelState.IsValid)
            {
                int dem = 1;
                foreach (var item in db.DONHANG)
                {
                    if (item.MaDH == dem)
                        dem++;
                }
                dONHANG.MaDH = dem;
                db.DONHANG.Add(dONHANG);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKH = new SelectList(db.KHACHHANG, "MaKH", "Ho", dONHANG.MaKH);
            ViewBag.MaKM = new SelectList(db.KHUYENMAI, "MaKM", "TenKM", dONHANG.MaKM);
            ViewBag.MaPTTT = new SelectList(db.PTTT, "MaPTTT", "TenPTTT", dONHANG.MaPTTT);
            return View(dONHANG);
        }

        // GET: Admin/DONHANGs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONHANG dONHANG = db.DONHANG.Find(id);
            if (dONHANG == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKH = new SelectList(db.KHACHHANG, "MaKH", "Ho", dONHANG.MaKH);
            ViewBag.MaKM = new SelectList(db.KHUYENMAI, "MaKM", "TenKM", dONHANG.MaKM);
            ViewBag.MaPTTT = new SelectList(db.PTTT, "MaPTTT", "TenPTTT", dONHANG.MaPTTT);
            return View(dONHANG);
        }

        // POST: Admin/DONHANGs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "MaDH,NoiGiao,NgayDat,NhanXet,MaKH,MaKM,MaPTTT,TamTinh,ThanhTien,MaTrangThai")] DONHANG dONHANG)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dONHANG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKH = new SelectList(db.KHACHHANG, "MaKH", "Ho", dONHANG.MaKH);
            ViewBag.MaKM = new SelectList(db.KHUYENMAI, "MaKM", "TenKM", dONHANG.MaKM);
            ViewBag.MaPTTT = new SelectList(db.PTTT, "MaPTTT", "TenPTTT", dONHANG.MaPTTT);
            return View(dONHANG);
        }

        // GET: Admin/DONHANGs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONHANG dONHANG = db.DONHANG.Find(id);
            if (dONHANG == null)
            {
                return HttpNotFound();
            }
            return View(dONHANG);
        }

        // POST: Admin/DONHANGs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DONHANG dONHANG = db.DONHANG.Find(id);
            db.DONHANG.Remove(dONHANG);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DryFood/DryFood/Areas/Admin/Views/DONHANGs/Create.cshtml
@model DryFood.Areas.Admin.Data.DONHANG

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DONHANG</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.NoiGiao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoiGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayDat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhanXet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhanXet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhanXet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaKH, "MaKH", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaKH", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaKM, "MaKM", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaKM", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaPTTT, "MaPTTT", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaPTTT", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPTTT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TamTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TamTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TamTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThanhTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThanhTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThanhTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaTrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaTrangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaTrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DryFood/DryFood/Areas/Admin/Views/DONHANGs/Delete.cshtml
@model DryFood.Areas.Admin.Data.DONHANG

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DONHANG</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NoiGiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiGiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhanXet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhanXet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TamTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TamTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThanhTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThanhTien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaTrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaTrangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KHACHHANG.Ho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KHACHHANG.Ho)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KHUYENMAI.TenKM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KHUYENMAI.TenKM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PTTT.TenPTTT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PTTT.TenPTTT)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DryFood/DryFood/Areas/Admin/Views/DONHANGs/Details.cshtml
@model DryFood.Areas.Admin.Data.DONHANG

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>DONHANG</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NoiGiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiGiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhanXet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhanXet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TamTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TamTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThanhTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThanhTien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaTrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaTrangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KHACHHANG.Ho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KHACHHANG.Ho)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KHUYENMAI.TenKM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KHUYENMAI.TenKM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PTTT.TenPTTT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PTTT.TenPTTT)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaDH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DryFood/DryFood/Areas/Admin/Views/DONHANGs/Edit.cshtml
@model DryFood.Areas.Admin.Data.DONHANG

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DONHANG</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaDH)

        <div class="form-group">
            @Html.LabelFor(model => model.NoiGiao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoiGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayDat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhanXet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhanXet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhanXet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaKH, "MaKH", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaKH", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaKM, "MaKM", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaKM", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaPTTT, "MaPTTT", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaPTTT", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPTTT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TamTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TamTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TamTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThanhTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThanhTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThanhTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaTrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaTrangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaTrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DryFood/DryFood/Areas/Admin/Views/DONHANGs/Index.cshtml
@model IEnumerable<DryFood.Areas.Admin.Data.DONHANG>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}

<div class="body_right_top">
    <div class="body_right_top_left">
        <p class="right_top_left_title">Danh sách đơn hàng</p>
    </div>
    <div class="body_right_top_right">
        <button class="add-new-item" onclick="location.href='@Url.Action("Create", "DONHANGs")'">
            <i class="fas fa-plus"></i>
            Thêm DH
        </button>
    </div>
</div>
<div class="body_right_bottom">
    <table class="table myAdTable">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NoiGiao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayDat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NhanXet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TamTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ThanhTien)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaTrangThai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KHACHHANG.Ho)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KHUYENMAI.TenKM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PTTT.TenPTTT)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NoiGiao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayDat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NhanXet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TamTinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThanhTien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaTrangThai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KHACHHANG.Ho)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KHUYENMAI.TenKM)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PTTT.TenPTTT)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.MaDH }) |
                    @Html.ActionLink("Details", "Details", new { id = item.MaDH }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.MaDH })
                </td>
            </tr>
        }

    </table>
</div>