DryFood/DryFood/Areas/Admin/Controllers/NHACUNGUNGsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DryFood.Areas.Admin.Data;

namespace DryFood.Areas.Admin.Controllers
{
    public class NHACUNGUNGsController : Controller
    {
        private dryfoodEntities db = new dryfoodEntities();

        // GET: Admin/NHACUNGUNGs
        public ActionResult Index()
        {
            return View(db.NHACUNGUNG.ToList());
        }

        // GET: Admin/NHACUNGUNGs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHACUNGUNG nHACUNGUNG = db.NHACUNGUNG.Find(id);
            if (nHACUNGUNG == null)
            {
                return HttpNotFound();
            }
            return View(nHACUNGUNG);
        }

        // GET: Admin/NHACUNGUNGs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/NHACUNGUNGs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNCC,TenNCC,SDTNCC")] NHACUNGUNG nHACUNGUNG)
        {
            if (ModelState.IsValid)
            {
                db.NHACUNGUNG.Add(nHACUNGUNG);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nHACUNGUNG);
        }

        // GET: Admin/NHACUNGUNGs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHACUNGUNG nHACUNGUNG = db.NHACUNGUNG.Find(id);
            if (nHACUNGUNG == null)
            {
                return HttpNotFound();
            }
            return View(nHACUNGUNG);
        }

        // POST: Admin/NHACUNGUNGs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNCC,TenNCC,SDTNCC")] NHACUNGUNG nHACUNGUNG)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nHACUNGUNG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nHACUNGUNG);
        }

        // GET: Admin/NHACUNGUNGs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHACUNGUNG nHACUNGUNG = db.NHACUNGUNG.Find(id);
            if (nHACUNGUNG == null)
            {
                return HttpNotFound();
            }
            return View(nHACUNGUNG);
        }

        // POST: Admin/NHACUNGUNGs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NHACUNGUNG nHACUNGUNG = db.NHACUNGUNG.Find(id);
            db.NHACUNGUNG.Remove(nHACUNGUNG);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DryFood/DryFood/Areas/Admin/Views/NHACUNGUNGs/Create.cshtml
@model DryFood.Areas.Admin.Data.NHACUNGUNG

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NHACUNGUNG</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDTNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDTNCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDTNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DryFood/DryFood/Areas/Admin/Views/NHACUNGUNGs/Delete.cshtml
@model DryFood.Areas.Admin.Data.NHACUNGUNG

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NHACUNGUNG</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDTNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDTNCC)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DryFood/DryFood/Areas/Admin/Views/NHACUNGUNGs/Details.cshtml
@model DryFood.Areas.Admin.Data.NHACUNGUNG

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>NHACUNGUNG</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDTNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDTNCC)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaNCC }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DryFood/DryFood/Areas/Admin/Views/NHACUNGUNGs/Edit.cshtml
@model DryFood.Areas.Admin.Data.NHACUNGUNG

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NHACUNGUNG</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNCC)

        <div class="form-group">
            @Html.LabelFor(model => model.TenNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDTNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDTNCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDTNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DryFood/DryFood/Areas/Admin/Views/NHACUNGUNGs/Index.cshtml
@model IEnumerable<DryFood.Areas.Admin.Data.NHACUNGUNG>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}

<div class="body_right_top">
    <div class="body_right_top_left">
        <p class="right_top_left_title">Danh sách nhà cung ứng</p>
    </div>
    <div class="body_right_top_right">
        <button class="add-new-item" onclick="location.href='@Url.Action("Create", "NHACUNGUNGs")'">
            <i class="fas fa-plus"></i>
            Thêm NCC
        </button>
    </div>
</div>
<div class="body_right_bottom">
    <table class="table myAdTable">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenNCC)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SDTNCC)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TenNCC)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SDTNCC)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.MaNCC }) |
                    @Html.ActionLink("Details", "Details", new { id = item.MaNCC }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.MaNCC })
                </td>
            </tr>
        }

    </table>
</div>