Controllers/DryFoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DryFood.Areas.Admin.Data;

namespace DryFood.Controllers
{
    public class DryFoodController : Controller
    {
        dryfoodEntities db = new dryfoodEntities();

        // GET: DryFood
        public ActionResult Index()
        {
            var dsSanPhamMoi = LaySanPhamMoi(5);
            return View(dsSanPhamMoi);
        }
        private List<SANPHAM> LaySanPhamMoi(int soluong)
        {
            return db.SANPHAM.OrderByDescending(sp => sp.NgayNhap).Take(soluong).ToList();
        }
        private List<SANPHAM> LaySanPhamHot(int soluong)
        {
            return db.SANPHAM.OrderByDescending(sp => sp.SoLanBan).Take(soluong).ToList();
        }
        public ActionResult DanhSachSanPham()
        {
            return View(db.SANPHAM.ToList());
        }
        public ActionResult Details(int id)
        {
            var sanPham = db.SANPHAM.FirstOrDefault(s => s.MaSP == id);
            //ViewBag.Category= new 
            return View(sanPham);
        }
        public ActionResult LayLoai()
        {
            var dsLoai = db.LOAI.ToList();
            return PartialView(dsLoai);
        }
        public ActionResult SPTheoLoai(int id)
        {
            var dsSPTheoLoai = db.SANPHAM.Where(sp => sp.MaLoai == id).ToList();
            return View("DanhSachSanPham", dsSPTheoLoai);
        }

        //Tìm kiếm
        // GET: Link
        public ActionResult Index(string searchString)
        {
            var links = from l in db.SANPHAM // lấy toàn bộ liên kết
                        select l;

            if (!String.IsNullOrEmpty(searchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
            {
                links = links.Where(s => s.TenSP.Contains(searchString)); //lọc theo chuỗi tìm kiếm
            }
            return View(links);
        }
    }
}

Views/DryFood/DanhSachSanPham.cshtml
@using DryFood.Areas.Admin.Data
@model IEnumerable<SANPHAM>
@{
    ViewBag.Title = "DanhSachSanPham";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<body class="goto-here">

    <div class="hero-wrap hero-bread" style="background-image: url('/Theme/images/all.jpg');">
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"><span class="mr-2"><a href="#">Home</a></span> <span>Products</span></p>
                    <h1 class="mb-0 bread">Products</h1>
                </div>
            </div>
        </div>
    </div>

    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-10 mb-5 text-center">
                    <ul class="product-category">
                        <li><a href="@Url.Action("DanhSachSanPham", "DryFood")"@* class="active"*@>All</a></li>
                        @Html.Action("LayLoai","DryFood")
                        @*<li><a href="#">Vegetables</a></li>
                        <li><a href="#">Fruits</a></li>
                        <li><a href="#">Dried</a></li>
                        <li><a href="#">Others</a></li>*@
                    </ul>
                </div>
            </div>
            <div class="row">
                @foreach (var SANPHAM in Model)
                {
                    /*col-md-6 */
                    <div class="col-lg-3 ftco-animate" style="max-width: 20%">
                        <div class="product">
                            <a href="#" class="img-prod">
                                <img class="img-fluid center1" src="~/Images/@SANPHAM.AnhSP" alt="Colorlib Template" style="height: 200px;">
                                @*<div class="overlay"></div>*@
                            </a>
                            <div class="text py-3 pb-4 px-3 text-center">
                                <h3 style="height: 42px"><a href="#">@SANPHAM.TenSP</a></h3>
                                <div class="d-flex">
                                    <div class="pricing">
                                        <p class="price"><span>@SANPHAM.GiaBan</span>đ</p>
                                    </div>
                                </div>
                                <div class="bottom-area d-flex px-3">
                                    <div class="m-auto d-flex">
                                        <a href="@Url.Action("Details", "DryFood", new { id = SANPHAM.MaSP })" class="add-to-cart d-flex justify-content-center align-items-center text-center">
                                            <span><i class="ion-ios-menu"></i></span>
                                        </a>
                                        <a href="@Url.Action("ThemVaoGio", "Cart", new { sanPhamID = SANPHAM.MaSP})" class="buy-now d-flex justify-content-center align-items-center mx-1">
                                            <span><i class="ion-ios-cart"></i></span>
                                        </a>
                                        <a href="#" class="heart d-flex justify-content-center align-items-center ">
                                            <span><i class="ion-ios-heart"></i></span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="row mt-5">
                <div class="col text-center">
                    <div class="block-27">
                        <ul>
                            <li><a href="#">&lt;</a></li>
                            <li class="active"><span>1</span></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                            <li><a href="#">&gt;</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- loader -->


    <script src="~/Theme/js/jquery.min.js"></script>
    <script src="~/Theme/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/Theme/js/popper.min.js"></script>
    <script src="~/Theme/js/bootstrap.min.js"></script>
    <script src="~/Theme/js/jquery.easing.1.3.js"></script>
    <script src="~/Theme/js/jquery.waypoints.min.js"></script>
    <script src="~/Theme/js/jquery.stellar.min.js"></script>
    <script src="~/Theme/js/owl.carousel.min.js"></script>
    <script src="~/Theme/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Theme/js/aos.js"></script>
    <script src="~/Theme/js/jquery.animateNumber.min.js"></script>
    <script src="~/Theme/js/bootstrap-datepicker.js"></script>
    <script src="~/Theme/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/Theme/js/google-map.js"></script>
    <script src="~/Theme/js/main.js"></script>
    <script src="~/Theme/js/site.js"></script>
    <script>
        $(document).ready(function () {
            $('.product-category').find('[href="' + window.location.pathname + '"]').addClass('active');
        });
    </script>
</body>
</html>

Views/DryFood/LayLoai.cshtml
@using DryFood.Areas.Admin.Data
@model IEnumerable<LOAI>

@foreach (var loai in Model)
{
    <li>
        <a href="@Url.Action("SPTheoLoai", "DryFood", new { id=loai.MaLoai })">@loai.TenLoai</a>
    </li>
}